### ISSUE TITLE
Error creating new connector using Connector Designer

### ISSUE THREAD

**Issue by jubba2001** [i2group/analyze-deployment-tooling#43]
**Describe the bug**
Connector Designer does not create a new connector when "Create" button is pressed.
No visible errors occur.

**To Reproduce**

1. Goto https://i2analyze.eia:9443/connector-designer/connectors
2. Press "New connector" button
3. Select connector name and schema files, Data source type: SQL, press "Continue" button.
5. Select "Database type: MS_SQL", Server location (address:port), Username, Password. Select the required Database from the list.
6. Press "Create" button
7. The text "Creating connector" appears, then disappears.
8. The "Create" button becomes available again. No visible errors occur.
9. No connectors created.

**Hardware and Software information**
Fill in the following information:

- OS + version: [Oracle Linux Server 8.10]]
- Architecture: [x64]
- Software Version: [v3.0.1]
- Docker version: [26.1.3]
- VS Code version: [-]
- Environment type: [config-dev]
- Deployment pattern: [-]

**Additional context**
The error hidden inside container logs:

`> docker logs connector_designer.con-des-default_4.4.4`

```
(node:72) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)
Compiling connector
FileSystemError: Unable to compile Connector SDK
        CausedBy: [Error] Command failed with code 5
    at ConnectorSdkService.compileSdk (/opt/app-root/src/dist/services/connectorSdk/connectorSdk.service.js:88:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectorService.createConnector (/opt/app-root/src/dist/features/connector/connector.service.js:43:13)
    at async ConnectorController.add (/opt/app-root/src/dist/features/connector/connector.controller.js:32:20)
    at async /opt/app-root/src/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /opt/app-root/src/node_modules/@nestjs/core/router/router-proxy.js:9:17
    at async /opt/app-root/src/node_modules/@nestjs/core/router/router-explorer.js:177:17
```

**Comment by Anthony-Johnson-i2** [comment]
Hi @jubba2001 

Connector Designer problems are handled via the standard support channels rather than through GitHub issues.

We do have an active case with a customer regarding the Create Button not creating a connector that has exactly the same error signature as you are showing here. We went back to that customer asking for more information but have not had a response yet,  was that you? 

If you have not already done so then you should use this form to raise a ticket and we can progress this via the official channels.

[Raise a ticket](https://i2group.com/support-request)

Thank you.

**Comment by Anthony-Johnson-i2** [comment]
Closing this issue as Connector Designer related queries are handled as mentioned above.
